#!/usr/bin/env bash
# Sync the literal agent-injected context (communication.md) into README.md
# between the communication:begin/end markers.
set -euo pipefail
cd "$(dirname "$0")"

SRC=plugins/blunt/context/communication.md
README=README.md
BEGIN='<!-- communication:begin (generated by ./build.sh — do not edit) -->'
END='<!-- communication:end -->'

grep -qF -- "$BEGIN" "$README" || { echo "build.sh: begin marker missing from $README" >&2; exit 1; }
grep -qF -- "$END" "$README" || { echo "build.sh: end marker missing from $README" >&2; exit 1; }

tmp=$(mktemp)
awk -v b="$BEGIN" -v e="$END" -v src="$SRC" '
  $0 == b {
    print
    print "```markdown"
    while ((getline line < src) > 0) print line
    close(src)
    print "```"
    skip=1; next
  }
  $0 == e { skip=0 }
  !skip { print }
' "$README" > "$tmp"
mv "$tmp" "$README"
echo "build.sh: injected $SRC into $README"
