#!/usr/bin/env bash
# Sync the literal agent-injected context (communication.md) into README.md
# between the communication:begin/end markers, hard-wrapped to fit a code
# fence (GitHub does not soft-wrap fenced blocks).
set -euo pipefail
cd "$(dirname "$0")"

SRC=plugins/blunt/context/communication.md
README=README.md
WIDTH=80
BEGIN='<!-- communication:begin (generated by ./build.sh — do not edit) -->'
END='<!-- communication:end -->'

grep -qF -- "$BEGIN" "$README" || { echo "build.sh: begin marker missing from $README" >&2; exit 1; }
grep -qF -- "$END" "$README" || { echo "build.sh: end marker missing from $README" >&2; exit 1; }

# Wrap at WIDTH characters, hanging-indenting list continuations by 2 spaces.
wrapped=$(mktemp)
perl -CSD -e '
  my $w = shift;
  while (<>) {
    chomp;
    if (!/\S/ || length() <= $w) { print "$_\n"; next; }
    my ($indent) = /^([ \t]*)/;
    my $hang = $indent . (/^[ \t]*(?:[*+-]|\d+[.)])[ \t]/ ? "  " : "");
    s/^[ \t]*//;
    my $cur = $indent;
    my $first = 1;
    for my $word (split /[ \t]+/) {
      if ($first) { $cur .= $word; $first = 0 }
      elsif (length($cur) + 1 + length($word) <= $w) { $cur .= " " . $word }
      else { print "$cur\n"; $cur = $hang . $word }
    }
    print "$cur\n";
  }
' "$WIDTH" "$SRC" > "$wrapped"

tmp=$(mktemp)
awk -v b="$BEGIN" -v e="$END" -v src="$wrapped" '
  $0 == b {
    print
    print "```markdown"
    while ((getline line < src) > 0) print line
    close(src)
    print "```"
    skip=1; next
  }
  $0 == e { skip=0 }
  !skip { print }
' "$README" > "$tmp"
mv "$tmp" "$README"
rm -f "$wrapped"
echo "build.sh: injected $SRC into $README"
